name: "Perl::Critic"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  perlcritic:
    name: "Perl::Critic"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Run Perl::Critic" 
      uses: Difegue/action-perlcritic@2.1.0
      with:
        args: --brutal ./cgi/*.pl ./*.pm
